services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockhol,
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config/jellyfin:/config
      - /mnt/downloads:/mnt/library
    ports:
      - "8096:8096"
    restart: unless-stopped

  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - PUID=1000
      - PUID=1000
      - TZ=Europe/Stockholm
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode
    volumes:
      - ./config/tdarr:/config
      - /mnt/downloads:/downloads
    ports:
      - "8265:8265"
      - "8266:8266"
    restart: unless-stopped
